name: Budibase Release
concurrency: release

on:
 push:
    branches:
      - master
    paths:
      - '.aws/**'
      - '.github/**'
      - 'charts/**'
      - 'packages/**'
      - 'scripts/**'
      - 'package.json'
      - 'yarn.lock'
      - 'package.json'
      - 'yarn.lock'
 workflow_dispatch:
  inputs:
    versioning:
      type: choice
      description: "Versioning type: patch, minor, major"
      default: patch
      options:
        - patch
        - minor
        - major
      required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Fail if branch is not master
        if: github.ref != 'refs/heads/master' 
        run: | 
          echo "Ref is not master, you must run this job from master."
          exit 1
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install Pro
        run: yarn install:pro master

      - run: yarn
      - run: yarn bootstrap
      - run: yarn lint
      - run: yarn build
      - run: yarn build:sdk
      - run: yarn test

      - name: Build/release Docker images
        run: | 
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          yarn build
          yarn build:docker
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_API_KEY }}
          BUDIBASE_RELEASE_VERSION: test



